### ISSUE TITLE
update title text

### ISSUE THREAD

**Issue by jmeyers314** [DarkEnergyScienceCollaboration/chroma#7]
Hey @drphilmarshall, do you have access to change the title text for this repo?  (I don't, but I see that you're an LSSTDESC org "owner", so I'm hoping you do).  Can you change the bit that still refers to "darkenergysciencecollaboration.github.io" to "LSSTDESC.github.io", please?

Thanks!

**Comment by drphilmarshall** [comment]
Done! :-)
